name: Simple Cross-Platform Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Debug environment
      run: |
        echo "=== macOS Environment ==="
        sw_vers
        echo "=== Xcode tools ==="
        xcode-select --print-path
        echo "=== Python info ==="
        python --version
        pip --version
        echo "=== Project Structure ==="
        ls -la
        echo "=== Source Structure ==="
        ls -la src/notebooklm_converter/
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase
        pip install ebooklib==0.18
        pip install beautifulsoup4==4.12.2
        pip install python-docx==0.8.11
        pip install pillow==10.0.1
        pip install requests==2.31.0
        pip install reportlab==4.0.4
    
    - name: Create icon
      run: |
        mkdir -p src/notebooklm_converter/resources
        cd src/notebooklm_converter/resources
        python -c "from PIL import Image; img = Image.new('RGBA', (512, 512), (70, 130, 180, 255)); img.save('icon-512.png')"
        echo "Icon created"
        ls -la
    
    - name: Build app
      run: |
        echo "=== Creating macOS app ==="
        briefcase create macOS
        echo "=== Building macOS app ==="
        briefcase build macOS
        echo "=== Packaging macOS app ==="
        briefcase package macOS --adhoc-sign
        echo "=== Checking results ==="
        if [ -d "dist" ]; then
          echo "Dist folder contents:"
          ls -la dist/
        else
          echo "ERROR: No dist folder found!"
        fi
        if [ -d "build" ]; then
          echo "Build folder contents:"
          ls -la build/
        fi
    
    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: |
          dist/*.dmg
          build/notebooklm-converter/macos/app/
      if: always()

  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Debug environment
      run: |
        echo "=== Windows Environment ==="
        echo "OS: $env:OS"
        echo "Architecture: $env:PROCESSOR_ARCHITECTURE"
        python --version
        pip --version
        echo "=== Project Structure ==="
        dir
        echo "=== Source Structure ==="
        dir src\notebooklm_converter
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase
        pip install ebooklib==0.18
        pip install beautifulsoup4==4.12.2
        pip install python-docx==0.8.11
        pip install pillow==10.0.1
        pip install requests==2.31.0
        pip install reportlab==4.0.4
    
    - name: Create icon
      run: |
        mkdir -Force src\notebooklm_converter\resources
        cd src\notebooklm_converter\resources
        python -c "from PIL import Image; img = Image.new('RGBA', (512, 512), (70, 130, 180, 255)); img.save('icon-512.png')"
        echo "Icon created"
        dir
    
    - name: Build app
      run: |
        echo "=== Creating Windows app ==="
        briefcase create windows
        echo "=== Building Windows app ==="
        briefcase build windows
        echo "=== Packaging Windows app ==="
        briefcase package windows
        echo "=== Checking results ==="
        if (Test-Path "dist") {
          echo "Dist folder contents:"
          dir dist
        } else {
          echo "ERROR: No dist folder found!"
        }
        if (Test-Path "build") {
          echo "Build folder contents:"
          dir build
        }
    
    - name: Upload Windows app
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: |
          dist/*.msi
          build/notebooklm-converter/windows/app/
      if: always()
